# yaml-language-server: $schema=https://schema.blue-build.org/module-v1.json
modules:
  - type: dnf
    remove:
      packages:
        - NetworkManager
        - bluez
    install:
      install-weak-deps: false
      packages:
        # USBGuard
        - usbguard
        - usbuard-notifier
        - usbguard-selinux
        - usbguard-dbus
    group-install:
      packages:
        - fonts
